ARG ALPINE_VERSION=3.17.1
ARG SQUASHFSTOOLS_VERSION=4.5.1-r1

FROM alpine:$ALPINE_VERSION

ARG SQUASHFSTOOLS_VERSION

RUN apk add --no-cache squashfs-tools=$SQUASHFSTOOLS_VERSION

ENTRYPOINT ["mksquashfs"]